---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: isala-me
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:*
spec:
  releaseName: isala-me
  chart:
    git: git@github.com:Iconicto/Kubernetes-Config.git
    path: charts/standard-chart
    ref: master
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      hosts:
      - host: isala.me
      - host: www.isala.me
      tls:
      - secretName: isala-me
        hosts:
        - isala.me
        - www.isala.me
    nameOverride: isala-me
    fullnameOverride: isala-me
    AppVersion: "1.0.0"
    image:
      name: isala-me
      repository: ghcr.io/mrsupiri/isala-me
      tag: build-6
    replicaCount: 1
    service:
      enabled: true
      type: ClusterIP
      port: 80
