apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql
  namespace: default
spec:
  encryptedData:
    postgresql-password: AgDEZ3IUBJv705UEvok0iVuBB8UpggNGXf07ciLwEOPNwT/u8kTCV+/YFMDYSISTiDQCsWuTKdu2uuH0wAOPhpht0c6WuGYhtq/Kot8+//yY4B5bFgspz6ubBNV+adUOKe5O1Bc1rOaFH3+4L2afj6RH5TBcxRMnA8z0yKerd2sfaEEm6zr604dw/x1lVK5qKEUlECDLF0acqBpaI0mAyutiREKFjf4nqNZs8he9zZ29u5cCZnxe7vltM2sJJZuHZaUEfLUkZFyRP1X2PC2C7pWHG/BvB9hgKzAAVgAAgXGdQ9c90/H+gghP8yC4JonuryQwWyMG1PDdBTk6C+FlPj+uOL2T3aBH/68XU4JMvELiGXtTRXRPjPCLIOArzyBuaOAfOWvD7sSSM3Pdsd+dx1Qyit1WB6hKxg4EiOj1uLLOThHpTxrNBUYAEk5TgEwjNbOQZAspOKQ79LBv6F3uqknZqVhrmLWZwZ6KJS/WLiPA7/pYy3oWqL1qDw7OkRB84mJjOG5QqcUWcxy+ks6zbuitkZow5KINhvG9r2olfzFVTJsnmmb7ACaQhn/q8H0QQRhDNfALcTpKewT1CcGXaHeKjaLE57uFL9tQFYmyjAuM56s+v2UTGFcsiy39oimI/oBXfCM8JSmP50audNcAydNDzfp5Zr5AH+rTiDfNjxPHO8F+DTUuf+w9IjFkxyO2GmS1n1Y2rNxvrrdACiMubRazg4bSBcs6II6il4u9iOQlEg==
  template:
    metadata:
      creationTimestamp: null
      name: postgresql
      namespace: default
    type: Opaque

